[package]
name = "nom-regex"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0-alpha1"
regex = "1.0"

[features]
alloc = []
default = ["alloc"]
